#!/bin/bash
# Configurar Google Drive con Service Account para EVA

echo "============================================================"
echo "CONFIGURACIÓN DE GOOGLE DRIVE - SERVICE ACCOUNT"
echo "============================================================"
echo ""
echo "PASO 1: CREAR SERVICE ACCOUNT"
echo "Entra a: https://console.cloud.google.com/iam-admin/serviceaccounts"
echo "1. Proyecto: 772801886632"
echo "2. + CREAR SERVICE ACCOUNT"
echo "3. Nombre: EVA-Drive-Access"
echo "4. CREAR Y CONTINUAR"
echo "5. Rol: Administrador de Drive (buscar 'drive.admin')"
echo "6. CONTINUAR → LISTO"
echo ""
echo "PASO 2: GENERAR CLAVE JSON"
echo "1. Clic en el email de la Service Account creada"
echo "2. Pestaña: CLAVES"
echo "3. AGREGAR CLAVE → Crear nueva clave → JSON"
echo "4. Se descarga archivo .json"
echo ""
echo "PASO 3: SUBIR CLAVE A EVA"
echo "Sube o copia el contenido del JSON a:"
echo "/home/adminbot/Proyecto EVA/empresas/serpentarius/vault/service_account.json"
echo "  (también compatible con: /home/adminbot/.config/opencode/secrets/vault/service_account.json)"
echo ""
echo "PASO 4: COMPARTIR DRIVE"
echo "1. Ve a https://drive.google.com"
echo "2. Selecciona archivos/carpetas"
echo "3. Compartir → Agrega el email de la Service Account"
echo "4. Permiso: Editor"
echo ""
echo "============================================================"
echo "DESPUÉS DE COMPLETAR, EJECUTA:"
echo "python3 /home/adminbot/Proyecto\ EVA/empresas/serpentarius/drive/verificar_drive.py"
echo "============================================================"
